model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
#    plot_mask_im_class: 17
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_in_channels: 3
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
#        mask_mode: 'sem'
        mask_mode: 'img'
        val_crop_h: 0 # compute loss on crops during validation to avoid issues with memory
        val_crop_w: 0


    ddconfig:
      double_z: True
      z_channels: 3
      resolution: [256,256]
      in_channels: 3 # rgb only
      out_ch: 3 # rgb only
      ch: 64
      ch_mult: [ 1,2,4,8 ]  # num_down = len(ch_mult)-1
      down_mult: [ 1,1,1 ]  # num_down = len(ch_mult)-1, we also use norm and gelu for each down
      num_res_blocks: 3 # num_res_blocks = len(ch_mult)-1
      attn_resolutions: [ ] # if we are using nonsquare, use h to denote the attn_resolution
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
#    batch_size: 2
#    batch_size: 1
    num_workers: 8
    wrap: True
    train:
      target: ldm.data.camelyon.camelyonSRTrain
      params:
        size_h: 256
        size_w: 256
        base_res: 256
        max_per_case: 5000
        mask_mode: 'img'
        downscale_f: 8
        degradation: pil_nearest
    validation:
      target: ldm.data.camelyon.camelyonSRValidation
      params:
        size_h: 256
        size_w: 256
        base_res: 256
        max_per_case: 5000
        mask_mode: 'img'
        downscale_f: 8
        degradation: pil_nearest
    test:
      target: ldm.data.camelyon.camelyonSRTest
      params:
        size_h: 256
        size_w: 256
        base_res: 256
        max_per_case: 5000
        mask_mode: 'img'
        downscale_f: 8
        degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
#        max_images: 8
        max_images: 1
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
#    accumulate_grad_batches: 12
#    accumulate_grad_batches: 24
    gpus: 0,1,2,3,
#    gpus: 0,
