model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
#    plot_mask_im_class: 17
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_in_channels: 1
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        mask_mode: 'sem'

    ddconfig:
      double_z: True
      z_channels: 3
#      resolution: [832,1488]
      resolution: [464, 832]
#      in_channels: 1 # sem mask only
#      in_channels: 2 # sem and ins masks only
#      in_channels: 3 # rgb only
      in_channels: 4 # rgb and sem mask
#      in_channels: 5 # rgb, sem and ins masks
      out_ch: 1 # sem mask only
#      out_ch: 2 # sem and ins masks only
#      out_ch: 3 # rgb only
#      out_ch: 4 # rgb and sem mask
#      out_ch: 5 # rgb, sem and ins masks
#      ch: 64
      ch: 32
      ch_mult: [ 1,2,4,8 ]  # num_down = len(ch_mult)-1
      down_mult: [ 1,2,1 ]  # num_down = len(ch_mult)-1, we also use norm and gelu for each down
      num_res_blocks: 3 # num_res_blocks = len(ch_mult)-1
      attn_resolutions: [ ] # if we are using nonsquare, use h to denote the attn_resolution
      dropout: 0.0


data:
  target: main.DataModuleFromConfig
  params:
#    batch_size: 12
#    batch_size: 2
    batch_size: 1
#    num_workers: 8
    wrap: True
    train:
      target: ldm.data.nuimages.nuimageSRTrain
      params:
#        size_h: 832
#        size_w: 1488
        size_h: 464
        size_w: 832
#        size_h: 440
#        size_w: 800
#        size_h: 224
#        size_w: 400
        mask_mode: 'sem'
        downscale_f: 8
        degradation: pil_nearest
    validation:
      target: ldm.data.nuimages.nuimageSRValidation
      params:
#        size_h: 832
#        size_w: 1488
        size_h: 464
        size_w: 832
#        size_h: 440
#        size_w: 800
#        size_h: 224
#        size_w: 400
        mask_mode: 'sem'
        downscale_f: 8
        degradation: pil_nearest
    test:
      target: ldm.data.nuimages.nuimageSRTest
      params:
#        size_h: 832
#        size_w: 1488
        size_h: 464
        size_w: 832
#        size_h: 440
#        size_w: 800
#        size_h: 224
#        size_w: 400
        mask_mode: 'sem'
        downscale_f: 8
        degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
#        max_images: 8
        max_images: 1
        increase_log_steps: True

  trainer:
    benchmark: True
#    accumulate_grad_batches: 2
#    accumulate_grad_batches: 12
    accumulate_grad_batches: 24
    gpus: 0,1,2,3,
#    gpus: 0,
